[licenses]
allow = [
  "MIT",
  "CC0-1.0",
  "ISC",
  "OpenSSL",
  "Unlicense",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "Apache-2.0",
  "Apache-2.0 WITH LLVM-exception",
  "Zlib",
]

unlicensed = "warn"
default = "warn"

private = { ignore = true }

[[licenses.clarify]]
name = "ring"
version = "*"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 }
]

[advisories]
ignore = [
    # Potential segfault in localtime_r invocations
    # We resolved this by patching chrono to use a version that doesn't depend on `time` v0.1
    # https://github.com/vectordotdev/vector/issues/9679
    "RUSTSEC-2020-0159",

    # No default limit put on request bodies
    # Ignoring as part of 0.24.2 release to avoid behavior change as input is trusted, but will be
    # included in 0.25.0
    "RUSTSEC-2022-0055"
]
