version: '3'

services:
  dogstatsd-client-agent:
    build: ./dogstastd_client
    environment:
      STATSD_HOST: datadog-agent
    depends_on:
      - datadog-agent
  dogstatsd-client-agent-vector:
    build: ./dogstastd_client
    environment:
      STATSD_HOST: datadog-agent-vector
    depends_on:
      - datadog-agent-vector
  datadog-agent:
    image: docker.io/datadog/agent:${CONFIG_VERSION}
    environment:
    - DD_API_KEY=${TEST_DATADOG_API_KEY:?TEST_DATADOG_API_KEY required}
    - DD_DD_URL=http://fakeintake-agent:80
    - DD_USE_DOGSTATSD=true
    - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
    - DD_HOSTNAME=datadog-agent
    - DD_PROCESS_AGENT_ENABLED=false
    - DD_APM_ENABLED=false
    - DD_LOGS_ENABLED=false
    - DD_CONTAINER_EXCLUDE="name:.*"
    - DD_ENABLE_PAYLOADS_EVENTS=false
    - DD_ENABLE_PAYLOADS_SERVICE_CHECKS=false
      #- DD_ENABLE_PAYLOADS_SKETCHES=false
  datadog-agent-vector:
    image: docker.io/datadog/agent:${CONFIG_VERSION}
    volumes:
      - ../../../tests/data/datadog-metrics-e2e.yaml:/etc/datadog-agent/conf.d/test.d/conf.yaml
    environment:
    - DD_API_KEY=${TEST_DATADOG_API_KEY:?TEST_DATADOG_API_KEY required}
      #- DD_DD_URL=http://runner:8081
    - DD_USE_DOGSTATSD=true
    - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
    - DD_HOSTNAME=datadog-agent-vector
    - DD_PROCESS_AGENT_ENABLED=false
    - DD_APM_ENABLED=false
    - DD_LOGS_ENABLED=false
    - DD_CONTAINER_EXCLUDE="name:.*"
      # TODO is there a way to further restrict metrics to just custom metrics?
    - DD_ENABLE_PAYLOADS_EVENTS=false
    - DD_ENABLE_PAYLOADS_SERVICE_CHECKS=false
      #- DD_ENABLE_PAYLOADS_SKETCHES=false
  fakeintake-agent:
    image: docker.io/datadog/fakeintake:${CONFIG_VERSION}
  fakeintake-agent-vector:
    image: docker.io/datadog/fakeintake:${CONFIG_VERSION}

networks:
  default:
    name: ${VECTOR_NETWORK}
