version: '3'

services:

  dogstatsd-client-agent:
    build: ./dogstatsd_client
    environment:
    - STATSD_HOST=datadog-agent
    depends_on:
      - datadog-agent

  dogstatsd-client-agent-vector:
    build: ./dogstatsd_client
    environment:
    - STATSD_HOST=datadog-agent-vector
    depends_on:
      - datadog-agent-vector

  # and sends metric data to
  # the `fakeintake-agent` service
  datadog-agent:
    image: docker.io/datadog/agent:${CONFIG_VERSION}
    depends_on:
      - fakeintake-agent
    environment:
    - DD_API_KEY=${TEST_DATADOG_API_KEY:?TEST_DATADOG_API_KEY required}
    - DD_HOSTNAME=datadog-agent
    - DD_ENABLE_PAYLOADS_EVENTS=false
    - DD_ENABLE_PAYLOADS_SERVICE_CHECKS=false
    - DD_CONTAINER_EXCLUDE="name:.*"
    volumes:
    # The Agent config file
    - ../../../tests/data/e2e/datadog/metrics/agent_only.yaml:/etc/datadog-agent/datadog.yaml

  # and sends metric data to
  # the `vector` service
  datadog-agent-vector:
    image: docker.io/datadog/agent:${CONFIG_VERSION}
    depends_on:
      - vector
    environment:
    - DD_API_KEY=${TEST_DATADOG_API_KEY:?TEST_DATADOG_API_KEY required}
    - DD_HOSTNAME=datadog-agent-vector
    - DD_ENABLE_PAYLOADS_EVENTS=false
    - DD_ENABLE_PAYLOADS_SERVICE_CHECKS=false
    - DD_CONTAINER_EXCLUDE="name:.*"
    volumes:
    # The Agent config file
    - ../../../tests/data/e2e/datadog/metrics/agent_vector.yaml:/etc/datadog-agent/datadog.yaml

  # Receives metric data from the `datadog-agent-vector` service and sends
  # to the `fakeintake-vector` service.
  vector:
    depends_on:
      - fakeintake-vector
    build:
      context: ${PWD}
      dockerfile: tests/data/e2e/datadog/Dockerfile
      args:
        - RUST_VERSION=${RUST_VERSION}
        - FEATURES=e2e-tests-datadog
    working_dir: /home/vector
    network_mode: host
    command:
      - "-vvv"
      - "-c"
      - "/home/vector/tests/data/e2e/datadog/metrics/vector.toml"
    volumes:
      - ${PWD}:/home/vector

  # Receives metric data from the `datadog-agent` service. Is queried by the test runner
  # which does the validation of consistency with the other fakeintake service.
  fakeintake-agent:
    image: docker.io/datadog/fakeintake:${CONFIG_VERSION}

  # Receives metric data from the `datadog-agent-vector` service. Is queried by the test runner
  # which does the validation of consistency with the other fakeintake service.
  fakeintake-vector:
    image: docker.io/datadog/fakeintake:${CONFIG_VERSION}

networks:
  default:
    name: ${VECTOR_NETWORK}

volumes:
  target: {}
